#!/usr/bin/env python3
"""Deterministic citation-anchor verifier for DingDuff cite-check.

Reads a proposals file (written by the orchestrating model), verifies every
proposed quote against the stored source files via normalized containment
matching, maps matches back to raw character offsets, and writes cites.json
(schema v1).

Offset semantics: all offsets are Unicode codepoint indices (Python ``str``
indices) into the file content decoded from UTF-8 bytes with NO newline
translation. Consumers slice the raw decoded text; they never re-derive
offsets.

stdout carries exactly one machine-readable JSON report; all diagnostics go
to stderr.

Exit codes:
    0  every citation anchored (or legitimately no_quote_claimed)
    1  one or more retryable anchor failures (cites.json was still written;
       failing citations are marked anchor_failed with a failure_reason)
    2  fatal: malformed proposals, unreadable/undecodable files, duplicate
       citation ids, or other structural errors
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
import unicodedata
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

SCRIPT_VERSION = "cite-check/verify_anchors.py 1.0"
SCHEMA_VERSION = 1

MIN_SEGMENT_NORM_CHARS = 10
SHORT_QUOTE_NORM_CHARS = 20
HINT_CONTEXT_RAW_CHARS = 200
MAX_PREFIX_SHRINK_WORDS = 30
MAX_CHAIN_START_CANDIDATES = 20

SINGLE_QUOTES = "‘’‚‛′"
DOUBLE_QUOTES = "“”„‟″«»"
DASHES = "‐‑‒–—―−"
ELLIPSIS = "…"

# HTML character references. CourtListener text (notably scraped state
# opinions — S.W. reporters and the like) carries literal &amp; / &#160; /
# &#13; into stored markdown. Decoding during normalization lets a clean
# quote match an entity-bearing source and vice versa.
#
# LOCKSTEP RULE: this named table and the numeric forms must match the
# viewer's JS port exactly (shared vectors in tests/normalization_vectors.json).
# Deliberately a fixed small table — NOT html.unescape's ~2000-name table —
# because the JS side must mirror it byte for byte.
HTML_ENTITIES = {
    "amp": "&", "lt": "<", "gt": ">", "quot": '"', "apos": "'",
    "nbsp": " ", "shy": "­",
    "sect": "§", "para": "¶", "deg": "°", "copy": "©", "reg": "®",
    "trade": "™", "middot": "·", "bull": "•",
    "mdash": "—", "ndash": "–", "hellip": "…",
    "ldquo": "“", "rdquo": "”", "lsquo": "‘", "rsquo": "’",
    "prime": "′", "Prime": "″",
    "ensp": " ", "emsp": " ", "thinsp": " ",
    "frac12": "½", "frac14": "¼", "frac34": "¾",
}
ENTITY_RE = re.compile(
    r"&(?:#(\d{1,7})|#[xX]([0-9a-fA-F]{1,6})|([a-zA-Z][a-zA-Z0-9]{1,30}));")

CITATION_ID_RE = re.compile(r"^c\d{3,}$")
BODY_END_RE = re.compile(r"^## Citing Cases", re.MULTILINE)
FOOTER_RE = re.compile(r"^\*Generated by DingDuff", re.MULTILINE)
WORD_HYPHEN_RE = re.compile(r"(?<=\w)-(?=\w)")
# Visible page-boundary markers that opinion_store inserts inline (replacing
# CL's invisible U+200B) — treated as zero-width during matching, the same
# way Cf chars (ZWSPs etc.) are handled below. Keep this regex in lockstep
# with PAGE_MARKER_RE in review_viewer.html.
PAGE_MARKER_RE = re.compile(r"<<pg\. \d+>>")


# ---------------------------------------------------------------------------
# Normalization
# ---------------------------------------------------------------------------

def _is_dropped(ch: str) -> bool:
    """Format characters (Cf) — soft hyphens, zero-width spaces, BiDi marks —
    are invisible and must not affect matching."""
    return unicodedata.category(ch) == "Cf"


def _decode_entity_at(text: str, i: int) -> Tuple[str, int]:
    """Effective character at position i: (decoded_char, raw_width).

    Decodes one HTML character reference if present (single pass — never
    re-decodes, so '&amp;#160;' yields the literal text '&#160;'); otherwise
    returns the literal character with width 1. Unknown names and invalid
    codepoints stay literal, so 'AT&T;' and 'R&D' are untouched.
    """
    if text[i] == "&":
        m = ENTITY_RE.match(text, i)
        if m:
            if m.group(3) is not None:
                named = HTML_ENTITIES.get(m.group(3))
                if named is not None:
                    return named, m.end() - i
            else:
                cp = int(m.group(1)) if m.group(1) is not None else int(m.group(2), 16)
                if 0 < cp <= 0x10FFFF and not (0xD800 <= cp <= 0xDFFF):
                    return chr(cp), m.end() - i
    return text[i], 1


def normalize_with_map(text: str) -> Tuple[str, List[int], List[int]]:
    """Normalize text for matching; return (normalized, starts, ends) where
    raw[starts[i]:ends[i]] is the raw span that produced normalized char i.

    Spans (rather than the previous single-index map) are required because an
    HTML character reference maps MANY raw chars to one normalized char; the
    old `idx[e-1] + 1` end convention would cut a trailing entity in half.

    Rules (in order): decode HTML character references; drop Cf chars;
    collapse Unicode whitespace runs (including whitespace entities) to one
    space; fold dashes to '-' with hyphen-linebreak de-hyphenation; fold
    curly quotes; expand the ellipsis char; per-char NFKC for the rest.
    """
    out: List[str] = []
    starts: List[int] = []
    ends: List[int] = []
    i, n = 0, len(text)
    while i < n:
        # Skip `<<pg. N>>` page markers entirely — contribute zero normalized
        # chars and no entries to starts/ends, so they're invisible to
        # quote matching but the position map still maps each emitted char
        # back to its true raw offset (past the marker).
        if text.startswith("<<pg. ", i):
            pm = PAGE_MARKER_RE.match(text, i)
            if pm:
                i = pm.end()
                continue
        ch, w = _decode_entity_at(text, i)
        if _is_dropped(ch):
            i += w
            continue
        if ch.isspace():
            run_start = i
            i += w
            while i < n:
                c2, w2 = _decode_entity_at(text, i)
                if c2.isspace() or _is_dropped(c2):
                    i += w2
                else:
                    break
            if out and out[-1] == " ":
                continue
            out.append(" ")
            starts.append(run_start)
            ends.append(i)
            continue
        if ch == "-" or ch in DASHES:
            # Hyphen-linebreak de-hyphenation: a hyphen directly after a
            # letter, followed by whitespace containing a newline and then a
            # lowercase letter, is a typesetting artifact — drop it and the
            # whitespace so "expecta-\ntion" matches "expectation".
            j = i + w
            saw_newline = False
            while j < n:
                c3, w3 = _decode_entity_at(text, j)
                if c3.isspace() or _is_dropped(c3):
                    if c3 in "\r\n":
                        saw_newline = True
                    j += w3
                else:
                    break
            if saw_newline and out and out[-1].isalpha() and j < n:
                cj, _ = _decode_entity_at(text, j)
                if cj.islower():
                    i = j
                    continue
            out.append("-")
            starts.append(i)
            ends.append(i + w)
            i += w
            continue
        if ch in SINGLE_QUOTES:
            out.append("'")
            starts.append(i)
            ends.append(i + w)
            i += w
            continue
        if ch in DOUBLE_QUOTES:
            out.append('"')
            starts.append(i)
            ends.append(i + w)
            i += w
            continue
        if ch == ELLIPSIS:
            for dot in "...":
                out.append(dot)
                starts.append(i)
                ends.append(i + w)
            i += w
            continue
        for f in unicodedata.normalize("NFKC", ch):
            if f.isspace():
                if out and out[-1] == " ":
                    continue
                f = " "
            out.append(f)
            starts.append(i)
            ends.append(i + w)
        i += w
    return "".join(out), starts, ends


def strip_norm(norm: str, starts: List[int], ends: List[int]
               ) -> Tuple[str, List[int], List[int]]:
    s, e = 0, len(norm)
    while s < e and norm[s] == " ":
        s += 1
    while e > s and norm[e - 1] == " ":
        e -= 1
    return norm[s:e], starts[s:e], ends[s:e]


def normalize_needle(text: str) -> str:
    norm, starts, ends = normalize_with_map(text)
    norm, _, _ = strip_norm(norm, starts, ends)
    return norm


def hyphenless_with_map(norm: str, starts: List[int], ends: List[int]
                        ) -> Tuple[str, List[int], List[int]]:
    """Remove hyphens between word characters (tier-2 matching), composing
    the span maps back to raw offsets."""
    out: List[str] = []
    out_starts: List[int] = []
    out_ends: List[int] = []
    n = len(norm)
    for k, ch in enumerate(norm):
        if ch == "-" and 0 < k < n - 1 and norm[k - 1].isalnum() and norm[k + 1].isalnum():
            continue
        out.append(ch)
        out_starts.append(starts[k])
        out_ends.append(ends[k])
    return "".join(out), out_starts, out_ends


def all_find(hay: str, needle: str) -> List[int]:
    if not needle:
        return []
    positions = []
    pos = hay.find(needle)
    while pos != -1:
        positions.append(pos)
        pos = hay.find(needle, pos + 1)
    return positions


# ---------------------------------------------------------------------------
# Documents
# ---------------------------------------------------------------------------

@dataclass
class Document:
    raw: str
    norm: str = field(init=False)
    starts: List[int] = field(init=False)
    ends: List[int] = field(init=False)
    body_end: int = field(init=False)
    header_end: int = field(init=False)
    _hyphenless: Optional[Tuple[str, List[int], List[int]]] = field(default=None, init=False)

    def __post_init__(self) -> None:
        self.norm, self.starts, self.ends = normalize_with_map(self.raw)
        m = BODY_END_RE.search(self.raw) or FOOTER_RE.search(self.raw)
        self.body_end = m.start() if m else len(self.raw)
        sep = self.raw.find("\n---\n")
        self.header_end = sep if sep != -1 else 0

    @property
    def hyphenless(self) -> Tuple[str, List[int], List[int]]:
        if self._hyphenless is None:
            self._hyphenless = hyphenless_with_map(self.norm, self.starts, self.ends)
        return self._hyphenless

    def raw_span(self, norm_start: int, norm_len: int) -> Tuple[int, int]:
        return self.starts[norm_start], self.ends[norm_start + norm_len - 1]


def read_document(path: Path) -> str:
    """Decode UTF-8 bytes directly — never text mode, so newline translation
    can never shift offsets."""
    return path.read_bytes().decode("utf-8")


def sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


# ---------------------------------------------------------------------------
# Matching
# ---------------------------------------------------------------------------

@dataclass
class Anchor:
    quote: str
    start: int
    end: int
    match: str


@dataclass
class Failure:
    reason: str
    hint: Optional[str] = None


def _candidate_spans(doc: Document, quote: str) -> Tuple[List[Tuple[int, int, str]], bool]:
    """All match spans for a (non-ellipsis) quote across tiers, as raw
    (start, end, label) tuples in tier order. Returns (spans, any_match_at_all)
    where any_match_at_all includes matches past body_end (used to distinguish
    only_in_citing_cases from not_found)."""
    spans: List[Tuple[int, int, str]] = []
    any_match = False

    raw_positions = all_find(doc.raw, quote)
    if raw_positions:
        any_match = True
        spans = [(p, p + len(quote), "exact") for p in raw_positions]
        if any(p < doc.body_end for p, _, _ in spans):
            return spans, any_match

    norm_quote = normalize_needle(quote)
    if norm_quote:
        norm_positions = all_find(doc.norm, norm_quote)
        if norm_positions:
            any_match = True
            spans = [(*doc.raw_span(p, len(norm_quote)), "normalized") for p in norm_positions]
            if any(p < doc.body_end for p, _, _ in spans):
                return spans, any_match

        hl_doc, hl_starts, hl_ends = doc.hyphenless
        dummy = [0] * len(norm_quote)
        hl_quote, _, _ = hyphenless_with_map(norm_quote, dummy, dummy)
        if hl_quote and hl_quote != norm_quote:
            hl_positions = all_find(hl_doc, hl_quote)
            if hl_positions:
                any_match = True
                spans = [
                    (hl_starts[p], hl_ends[p + len(hl_quote) - 1], "normalized")
                    for p in hl_positions
                ]
                if any(p < doc.body_end for p, _, _ in spans):
                    return spans, any_match

    return spans, any_match


def _case_insensitive_hint(doc: Document, quote: str) -> Optional[str]:
    norm_quote = normalize_needle(quote)
    if not norm_quote:
        return None
    pos = doc.norm.lower().find(norm_quote.lower())
    if pos == -1:
        return None
    start, end = doc.raw_span(pos, len(norm_quote))
    return doc.raw[start:end]


def _prefix_shrink_hint(doc: Document, quote: str) -> Optional[str]:
    """Find the closest region by shrinking the quote prefix word-by-word;
    return ~200 raw chars of surrounding context."""
    words = normalize_needle(quote).split(" ")
    upper = min(len(words) - 1, MAX_PREFIX_SHRINK_WORDS)
    for k in range(upper, 2, -1):
        prefix = " ".join(words[:k])
        pos = doc.norm.find(prefix)
        if pos != -1:
            start, _ = doc.raw_span(pos, len(prefix))
            lo = max(0, start - 40)
            return doc.raw[lo:lo + HINT_CONTEXT_RAW_CHARS]
    return None


def anchor_plain_quote(doc: Document, quote: str) -> Tuple[Optional[List[Anchor]], Optional[Failure], List[Dict[str, str]]]:
    warnings: List[Dict[str, str]] = []
    spans, any_match = _candidate_spans(doc, quote)
    in_body = [s for s in spans if s[0] < doc.body_end]
    if in_body:
        if len(in_body) > 1:
            warnings.append({"code": "multiple_matches",
                             "detail": f"{len(in_body)} occurrences; used first in-body match"})
        start, end, label = in_body[0]
        if start < doc.header_end:
            warnings.append({"code": "match_in_header",
                             "detail": "matched text sits in the caption/metadata header"})
        if len(normalize_needle(quote)) < SHORT_QUOTE_NORM_CHARS:
            warnings.append({"code": "short_quote",
                             "detail": f"normalized quote is {len(normalize_needle(quote))} chars; ambiguity-prone"})
        return [Anchor(doc.raw[start:end], start, end, label)], None, warnings
    if any_match:
        return None, Failure("only_in_citing_cases",
                             "the quote appears only in the Citing Cases section or footer, "
                             "not in the opinion body"), warnings
    ci = _case_insensitive_hint(doc, quote)
    if ci is not None:
        return None, Failure("case_mismatch", ci), warnings
    return None, Failure("not_found", _prefix_shrink_hint(doc, quote)), warnings


def _split_ellipsis_segments(norm_quote: str) -> List[str]:
    segments = [seg.strip() for seg in norm_quote.split("...")]
    # Leading/trailing ellipses are mere trimming markers — drop empty edges.
    while segments and not segments[0]:
        segments.pop(0)
    while segments and not segments[-1]:
        segments.pop()
    return segments


def anchor_ellipsis_quote(doc: Document, quote: str, max_gap: int) -> Tuple[Optional[List[Anchor]], Optional[Failure], List[Dict[str, str]]]:
    warnings: List[Dict[str, str]] = []
    norm_quote = normalize_needle(quote)
    segments = _split_ellipsis_segments(norm_quote)
    if not segments or any(seg == "" for seg in segments):
        return None, Failure("segment_too_short",
                             "ellipsis quote contains an empty segment"), warnings
    for seg in segments:
        if len(seg) < MIN_SEGMENT_NORM_CHARS:
            return None, Failure(
                "segment_too_short",
                f"segment '{seg}' is {len(seg)} normalized chars "
                f"(minimum {MIN_SEGMENT_NORM_CHARS}) — quote more of the passage"), warnings

    first_positions = [p for p in all_find(doc.norm, segments[0])]
    in_body_firsts = [p for p in first_positions if doc.starts[p] < doc.body_end]
    if not in_body_firsts:
        if first_positions:
            return None, Failure("only_in_citing_cases",
                                 "the first segment appears only past the opinion body"), warnings
        ci = _case_insensitive_hint(doc, segments[0])
        if ci is not None:
            return None, Failure("case_mismatch", ci), warnings
        return None, Failure("not_found", _prefix_shrink_hint(doc, segments[0])), warnings

    last_failure: Failure = Failure("not_found", None)
    for start_pos in in_body_firsts[:MAX_CHAIN_START_CANDIDATES]:
        chain: List[Tuple[int, int]] = [(start_pos, start_pos + len(segments[0]))]
        ok = True
        for seg in segments[1:]:
            prev_end = chain[-1][1]
            pos = doc.norm.find(seg, prev_end)
            if pos == -1:
                anywhere = doc.norm.find(seg)
                if anywhere == -1:
                    ci = _case_insensitive_hint(doc, seg)
                    last_failure = (Failure("case_mismatch", ci) if ci is not None
                                    else Failure("not_found", _prefix_shrink_hint(doc, seg)))
                else:
                    last_failure = Failure(
                        "not_found",
                        f"segment '{seg[:60]}' occurs only before the previous segment "
                        "— ellipsis segments must appear in document order")
                ok = False
                break
            if pos - prev_end > max_gap:
                last_failure = Failure(
                    "ellipsis_gap_too_large",
                    f"gap of {pos - prev_end} normalized chars between segments exceeds {max_gap}")
                ok = False
                break
            chain.append((pos, pos + len(seg)))
        if ok:
            if len(in_body_firsts) > 1:
                warnings.append({"code": "multiple_matches",
                                 "detail": f"first segment has {len(in_body_firsts)} in-body occurrences; "
                                           "used the first that completes the chain"})
            anchors = []
            for s, e in chain:
                raw_s, raw_e = doc.raw_span(s, e - s)
                anchors.append(Anchor(doc.raw[raw_s:raw_e], raw_s, raw_e, "normalized"))
            return anchors, None, warnings
    return None, last_failure, warnings


def anchor_quote(doc: Document, quote: str, max_gap: int):
    if "..." in quote or ELLIPSIS in quote:
        return anchor_ellipsis_quote(doc, quote, max_gap)
    return anchor_plain_quote(doc, quote)


def anchor_memo(memo: Document, cite_text: str, memo_context: Optional[str]):
    """Locate cite_text in the memo; returns ((start, end), failure)."""
    norm_cite = normalize_needle(cite_text)
    if not norm_cite:
        return None, Failure("not_found", "cite_text is empty after normalization")
    positions = all_find(memo.norm, norm_cite)
    if len(positions) == 1:
        return memo.raw_span(positions[0], len(norm_cite)), None
    if not positions:
        ci = _case_insensitive_hint(memo, cite_text)
        if ci is not None:
            return None, Failure("case_mismatch", ci)
        return None, Failure("not_found",
                             "cite_text does not appear in the memo — it must match the memo verbatim")
    if not memo_context:
        return None, Failure("ambiguous_in_memo",
                             f"cite_text occurs {len(positions)} times; provide a memo_context snippet")
    norm_ctx = normalize_needle(memo_context)
    ctx_positions = all_find(memo.norm, norm_ctx)
    if not ctx_positions:
        return None, Failure("memo_context_not_found",
                             "memo_context does not appear in the memo verbatim")
    if len(ctx_positions) > 1:
        return None, Failure("ambiguous_in_memo",
                             f"memo_context occurs {len(ctx_positions)} times; extend it until unique")
    cs = ctx_positions[0]
    ce = cs + len(norm_ctx)
    inner = memo.norm.find(norm_cite, cs, ce)
    if inner == -1:
        return None, Failure("cite_text_not_in_context",
                             "cite_text does not occur inside memo_context")
    return memo.raw_span(inner, len(norm_cite)), None


# ---------------------------------------------------------------------------
# Proposals validation & processing
# ---------------------------------------------------------------------------

class FatalError(Exception):
    pass


SOURCE_PASSTHROUGH_KEYS = (
    "type", "path", "cluster_id", "case_name", "citation",
    "code", "section", "statute_id", "jurisdiction", "missing",
    "title", "kind",
)

# "opinion"/"statute" are public hosted authorities the review panel re-fetches
# from DingDuff. A "document" is an attorney-supplied working file (a
# Restatement section, an off-CourtListener case, an opposing brief, a factual
# PDF): matched the same way, but it has no citing-cases appendix to guard and
# is delivered to the panel inline rather than fetched.
SOURCE_TYPES = ("opinion", "statute", "document")

CLUSTER_ID_LINE_RE = re.compile(r"^\*\*Cluster ID:\*\*\s*(\S+)", re.MULTILINE)


def validate_proposals(proposals: Any) -> None:
    if not isinstance(proposals, dict):
        raise FatalError("proposals must be a JSON object")
    if proposals.get("schema_version") != SCHEMA_VERSION:
        raise FatalError(
            f"proposals.schema_version must be {SCHEMA_VERSION}")
    memo = proposals.get("memo")
    if not isinstance(memo, dict) or not isinstance(memo.get("path"), str):
        raise FatalError("proposals.memo.path is required")
    sources = proposals.get("sources")
    if not isinstance(sources, dict) or not sources:
        raise FatalError("proposals.sources must be a non-empty object")
    for key, src in sources.items():
        if not isinstance(src, dict) or src.get("type") not in SOURCE_TYPES:
            raise FatalError(
                f"source '{key}': type must be one of {SOURCE_TYPES}")
        if src.get("missing"):
            continue
        if not isinstance(src.get("path"), str):
            raise FatalError(f"source '{key}': path is required unless missing=true")
    citations = proposals.get("citations")
    if not isinstance(citations, list) or not citations:
        raise FatalError("proposals.citations must be a non-empty list")
    seen_ids = set()
    for c in citations:
        if not isinstance(c, dict):
            raise FatalError("each citation must be an object")
        cid = c.get("id")
        if not isinstance(cid, str) or not CITATION_ID_RE.match(cid):
            raise FatalError(f"citation id '{cid}' must match c<NNN> (e.g. c001)")
        if cid in seen_ids:
            raise FatalError(f"duplicate citation id '{cid}'")
        seen_ids.add(cid)
        if c.get("source") not in sources:
            raise FatalError(f"citation '{cid}': unknown source '{c.get('source')}'")
        if not isinstance(c.get("cite_text"), str) or not c["cite_text"].strip():
            raise FatalError(f"citation '{cid}': cite_text is required")
        if not isinstance(c.get("proposition"), str) or not c["proposition"].strip():
            raise FatalError(f"citation '{cid}': proposition is required")
        if c.get("support_type") not in ("quotation", "paraphrase"):
            raise FatalError(f"citation '{cid}': support_type must be 'quotation' or 'paraphrase'")
        anchors = c.get("anchors_proposed", [])
        if c.get("no_quote_claimed"):
            continue
        if (not isinstance(anchors, list) or not anchors
                or not all(isinstance(a, dict) and isinstance(a.get("quote"), str)
                           and a["quote"].strip() for a in anchors)):
            raise FatalError(
                f"citation '{cid}': anchors_proposed must contain at least one quote "
                "(or set no_quote_claimed=true)")


def utc_now_iso() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z")


def run(proposals: Dict[str, Any], workdir: Path, max_gap: int,
        generated_by: Optional[str]) -> Tuple[Dict[str, Any], Dict[str, Any]]:
    """Process proposals; returns (cites_json, report)."""
    memo_path = workdir / proposals["memo"]["path"]
    if not memo_path.is_file():
        raise FatalError(f"memo file not found: {proposals['memo']['path']}")
    try:
        memo_doc = Document(read_document(memo_path))
    except UnicodeDecodeError as exc:
        raise FatalError(f"memo is not valid UTF-8: {exc}") from exc
    memo_doc.body_end = len(memo_doc.raw)  # memos have no citing-cases section
    memo_doc.header_end = 0

    warnings: List[Dict[str, str]] = []
    docs: Dict[str, Document] = {}
    out_sources: Dict[str, Dict[str, Any]] = {}
    for key, src in proposals["sources"].items():
        entry = {k: src[k] for k in SOURCE_PASSTHROUGH_KEYS if k in src}
        if src.get("missing"):
            entry["path"] = None
            entry["sha256"] = None
            entry["missing"] = True
            out_sources[key] = entry
            continue
        path = workdir / src["path"]
        if not path.is_file():
            raise FatalError(f"source '{key}' file not found: {src['path']}")
        try:
            docs[key] = Document(read_document(path))
        except UnicodeDecodeError as exc:
            raise FatalError(f"source '{key}' is not valid UTF-8: {exc}") from exc
        if src.get("type") == "document":
            # A working file has no citing-cases appendix or DingDuff footer;
            # the whole file is quotable. (Opinions keep the body guard; the
            # `## Citing Cases` / footer markers gate quoting to the body.)
            docs[key].body_end = len(docs[key].raw)
            docs[key].header_end = 0
        entry["sha256"] = sha256_file(path)
        if src.get("type") == "opinion" and src.get("cluster_id") is not None:
            m = CLUSTER_ID_LINE_RE.search(docs[key].raw)
            if m and m.group(1) != str(src["cluster_id"]):
                warnings.append({"id": key, "code": "cluster_id_mismatch",
                                 "detail": f"file says cluster {m.group(1)}, "
                                           f"proposal says {src['cluster_id']}"})
        out_sources[key] = entry

    out_citations: List[Dict[str, Any]] = []
    failed: List[Dict[str, Any]] = []
    unverifiable: List[Dict[str, Any]] = []
    by_status: Dict[str, int] = {"anchored": 0, "anchor_failed": 0, "no_quote_claimed": 0}

    for c in proposals["citations"]:
        cid = c["id"]
        source_key = c["source"]
        cite_warnings: List[Dict[str, str]] = []

        memo_anchor, memo_failure = anchor_memo(memo_doc, c["cite_text"], c.get("memo_context"))
        if memo_failure:
            failed.append({"id": cid, "source": source_key, "where": "memo",
                           "quote": c["cite_text"], "reason": memo_failure.reason,
                           "hint": memo_failure.hint})

        anchors: List[Anchor] = []
        source_failure_reason: Optional[str] = None
        src_entry = out_sources[source_key]
        if src_entry.get("missing"):
            source_failure_reason = "source_missing"
        elif not c.get("no_quote_claimed"):
            doc = docs[source_key]
            for proposed in c.get("anchors_proposed", []):
                quote = proposed["quote"]
                got, failure, w = anchor_quote(doc, quote, max_gap)
                for item in w:
                    cite_warnings.append({"id": cid, **item})
                if failure:
                    source_failure_reason = source_failure_reason or failure.reason
                    failed.append({"id": cid, "source": source_key, "where": "source",
                                   "quote": quote, "reason": failure.reason,
                                   "hint": failure.hint})
                else:
                    anchors.extend(got)

        if src_entry.get("missing"):
            status, failure_reason = "anchor_failed", "source_missing"
            unverifiable.append({"id": cid, "source": source_key, "reason": "source_missing"})
        elif memo_failure or source_failure_reason:
            status = "anchor_failed"
            failure_reason = source_failure_reason or memo_failure.reason
        elif c.get("no_quote_claimed"):
            status, failure_reason = "no_quote_claimed", None
        else:
            status, failure_reason = "anchored", None
        by_status[status] += 1

        entry: Dict[str, Any] = {
            "id": cid,
            "source": source_key,
            "cite_text": c["cite_text"],
            "memo_anchor": ({"start": memo_anchor[0], "end": memo_anchor[1]}
                            if memo_anchor else None),
            "proposition": c["proposition"],
            "support_type": c["support_type"],
            "anchors": [vars(a) for a in anchors],
            "status": status,
            # Review-binding hash: verdicts in review.json bind to this value,
            # so a verdict goes stale when the cite or proposition changes.
            "binds_to": hashlib.sha256(
                (c["cite_text"] + "\x00" + c["proposition"]).encode("utf-8")
            ).hexdigest(),
        }
        if c.get("pin") is not None:
            entry["pin"] = c["pin"]
        if failure_reason:
            entry["failure_reason"] = failure_reason
        out_citations.append(entry)
        warnings.extend(cite_warnings)

    generated_by_full = (f"{generated_by} ({SCRIPT_VERSION})" if generated_by
                         else SCRIPT_VERSION)
    cites = {
        "schema_version": SCHEMA_VERSION,
        "memo": {
            "path": proposals["memo"]["path"],
            "sha256": sha256_file(memo_path),
            "generated_at": utc_now_iso(),
            "generated_by": generated_by_full,
        },
        "sources": out_sources,
        "citations": out_citations,
    }
    report = {
        "ok": not failed,
        "citations_total": len(out_citations),
        "anchored": by_status["anchored"],
        "by_status": by_status,
        "failed": failed,
        "unverifiable": unverifiable,
        "warnings": warnings,
    }
    return cites, report


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--proposals", required=True, help="path to proposals.json")
    parser.add_argument("--out", required=True, help="path to write cites.json")
    parser.add_argument("--workdir", default=".",
                        help="directory against which relative paths resolve")
    parser.add_argument("--max-gap", type=int, default=2000,
                        help="max normalized-char gap between ellipsis segments")
    parser.add_argument("--generated-by", default=None,
                        help="label recorded in cites.json memo.generated_by")
    args = parser.parse_args(argv)

    workdir = Path(args.workdir)
    try:
        try:
            proposals = json.loads((workdir / args.proposals).read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            raise FatalError(f"cannot read proposals: {exc}") from exc
        validate_proposals(proposals)
        cites, report = run(proposals, workdir, args.max_gap, args.generated_by)
    except FatalError as exc:
        print(f"fatal: {exc}", file=sys.stderr)
        return 2

    out_path = workdir / args.out
    out_path.write_text(json.dumps(cites, ensure_ascii=False, indent=2) + "\n",
                        encoding="utf-8")
    print(json.dumps(report, ensure_ascii=False, indent=2))
    return 0 if report["ok"] else 1


if __name__ == "__main__":
    sys.exit(main())
